from typing import Dict


def build_response(user_message: str) -> Dict[str, str]:
    """
    Very simple placeholder assistant.
    In real projects this calls an AI model and custom business logic.
    """
    user_message = user_message.strip()

    if not user_message:
        return {
            "status": "error",
            "message": "Please provide a non-empty message."
        }

    if "summarize" in user_message.lower():
        hint = "a short summary."
    elif "email" in user_message.lower():
        hint = "a clear, polite email."
    else:
        hint = "a concise, helpful answer."

    reply = (
        "This is a demo response.\n\n"
        "In a real project, this would be generated by an AI model (GPT, etc.) "
        "and adapted to your specific business rules.\n\n"
        f"I will now try to provide {hint}"
    )

    return {
        "status": "ok",
        "message": reply
    }
